//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarneFunds.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        public Campaign()
        {
            this.Donations = new HashSet<Donation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<float> Goal { get; set; }
        public bool IsActive { get; set; }
        public bool IsComplete { get; set; }
        public bool PinToHomePage { get; set; }
    
        public virtual ICollection<Donation> Donations { get; set; }
    }
}
