//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarneFunds.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactAudit
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateArchived { get; set; }
        public string UserId { get; set; }
        public int ContactId { get; set; }
        public Nullable<System.DateTime> DateUnarchived { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Contact Contact { get; set; }
    }
}
